# Generated by Django 4.1.4 on 2023-01-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_recommender', '0007_favouritegenre_delete_favouritegenres'),
        ('portal', '0002_remove_customuser_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favourite_genres',
            field=models.ManyToManyField(through='film_recommender.FavouriteGenre', to='film_recommender.genre'),
        ),
    ]
