# Generated by Django 4.1.4 on 2023-05-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_customuser_favourite_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='master_token',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
