# Generated by Django 4.1.4 on 2023-05-04 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_customuser_master_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='master_token',
        ),
    ]
