version: "3.8"


services:
  app:
    image: recommend-portal
    container_name: app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000


  celery:
    image: recommend-portal
    container_name: celery
    command: celery -A FilmRecomendationSystem worker -B -l info


  redis:
    image: redis:alpine
    ports:
      - 6379:6379
