# Generated by Django 4.1.4 on 2022-12-22 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film_recommender', '0002_movie_duration_movie_original_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='tmpb_id',
            new_name='tmbd_id',
        ),
    ]
