# Generated by Django 4.1.4 on 2022-12-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_recommender', '0003_rename_tmpb_id_movie_tmbd_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tmbd_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
