# Generated by Django 4.1.4 on 2022-12-23 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film_recommender', '0004_alter_movie_tmbd_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyrecommendation',
            name='movies',
        ),
        migrations.AlterField(
            model_name='dailyrecommendedfilm',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='film_recommender.movie', verbose_name='Фильм дня'),
        ),
    ]
