# Generated by Django 4.1.4 on 2022-12-23 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film_recommender', '0005_remove_dailyrecommendation_movies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecommendedfilm',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_movies', to='film_recommender.movie', verbose_name='Фильм дня'),
        ),
        migrations.AlterField(
            model_name='dailyrecommendedfilm',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='film_recommender.dailyrecommendation', verbose_name='рекомендация'),
        ),
    ]
