# Generated by Django 4.1.4 on 2023-05-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_recommender', '0008_image_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='tmbd_id',
            new_name='tmdb_id',
        ),
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(to='film_recommender.tag', verbose_name='Теги'),
        ),
    ]
