# Generated by Django 4.1.4 on 2023-05-18 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film_recommender', '0009_tag_rename_tmbd_id_movie_tmdb_id_movie_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyrecommendedfilm',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='dailyrecommendedfilm',
            name='recommendation',
        ),
        migrations.DeleteModel(
            name='DailyRecommendation',
        ),
        migrations.DeleteModel(
            name='DailyRecommendedFilm',
        ),
    ]
