# Generated by Django 4.1.4 on 2023-05-31 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film_recommender', '0011_dailyrecommendedfilm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyrecommendedfilm',
            old_name='computed_rating',
            new_name='predicted_rating',
        ),
    ]
