# Generated by Django 4.1.4 on 2023-05-31 17:27

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):
    dependencies = [
        ('film_recommender', '0012_rename_computed_rating_dailyrecommendedfilm_predicted_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Жанр Translation',
                'db_table': 'film_recommender_genre_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name='MovieTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.TextField(verbose_name='Название')),
                ('overview', models.TextField(blank=True, null=True, verbose_name='Сюжет')),
            ],
            options={
                'verbose_name': 'Фильм Translation',
                'db_table': 'film_recommender_movie_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name='TagTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тег Translation',
                'db_table': 'film_recommender_tag_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='movie_title_gin',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='name',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='original_language',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='title',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
        migrations.AddField(
            model_name='tagtranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True,
                                                       on_delete=django.db.models.deletion.CASCADE,
                                                       related_name='translations', to='film_recommender.tag'),
        ),
        migrations.AddField(
            model_name='movietranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True,
                                                       on_delete=django.db.models.deletion.CASCADE,
                                                       related_name='translations', to='film_recommender.movie'),
        ),
        migrations.AddField(
            model_name='genretranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True,
                                                       on_delete=django.db.models.deletion.CASCADE,
                                                       related_name='translations', to='film_recommender.genre'),
        ),
        migrations.AlterUniqueTogether(
            name='tagtranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='movietranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='genretranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
