# Generated by Django 4.1.4 on 2023-06-04 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film_recommender', '0013_genretranslation_movietranslation_tagtranslation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('film_recommender.movie',),
        ),
    ]
