# Generated by Django 4.1.4 on 2023-06-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_recommender', '0015_movietranslation_image_url_alter_movie_released_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movietranslation',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
